Step3 로또 계산기 완료했습니다.
zunior-team/java-lotto-old pull request #14
Opened 2020-03-02 06:35 UTC by junwoochoi

생각보다 수정하기가 어렵네요..ㅠ

2020-03-03 15:17 UTC, gale34 commented on src/main/java/lotto/ManualLottoGenerator.java
> +    private final Scanner scanner = new Scanner(System.in);
이건 여기서 안쓰는것 같은데, 빼도 될것 같아요!

2020-03-03 15:24 UTC, gale34 commented on src/main/java/lotto/ResultsFactory.java
> +        final ArrayList<Result> parameterResults = new ArrayList<>(results);
results를 그대로 쓰지 않고, parameterResults로 한번 받아서 사용하신 이유가 있나요?

2020-03-03 15:28 UTC, gale34 commented on src/main/java/lotto/ManualLottoGenerator.java
> +    private void validateNumbes(List<Integer> inputNumbers) {
엇 오타가..
```suggestion
    private void validateNumbers(List<Integer> inputNumbers) {
```

2020-03-03 15:31 UTC, gale34 reviewed
코드 잘 보고 갑니다! 지엽적인 코맨트 몇개 남겼어요:)

2020-03-04 13:08 UTC, wonoh reviewed
딱히 코멘트 달게없는 코드네요!
고생하셨습니다.

2020-03-04 13:08 UTC, wonoh commented on src/test/java/lotto/LottoNoTest.java
> +@DisplayName("LottoNo 테스")
트

2020-03-04 13:08 UTC, wonoh commented on src/main/java/lotto/LottoShop.java
> +        }
이부분은 함수로 빼도 괜찮지 않을까요?

2020-03-04 15:18 UTC, cglee079 requested changes
수고하셨습니다 👍 
몇가지 코멘트를 남겨보았어용!

2020-03-04 15:18 UTC, cglee079 commented on src/main/java/lotto/LottoNo.java
> +        if (!isValid(number)) {
개인적인 생각일 수 있지만,,
`validate()`라는 추상화된 네이밍 메세지를, 다시 똑같은 추상화된 네이밍의 `isValid()` 메소드를 호출하는느낌이라..
`vaildate()`내이니 `isValidRange()`같이  한단계 더 구체화된 네이밍을 하는것도 괜찮겠다 라는 생각이들었어욥 👀

2020-03-04 15:18 UTC, cglee079 commented on src/main/java/lotto/LottoShop.java
> +        assert inputMoney != null && manualLottoInputs != null;
`assert`에 대해서 공부한적있는데,
`assert`를  `public` 메소드에서 사용하지 말라는 내용을 본적이 있어서 공유해봅니다.

[https://softwareengineering.stackexchange.com/questions/137158/is-it-better-to-use-assert-or-illegalargumentexception-for-required-method-param](https://softwareengineering.stackexchange.com/questions/137158/is-it-better-to-use-assert-or-illegalargumentexception-for-required-method-param) 

> 다시보니, 예전에, 자리에서 얘기했던거중에 `Assertion` 클래스랑 `assert`는 완전히 다른거였네요.......ㅋㅋ..

2020-03-04 15:18 UTC, cglee079 commented on src/main/java/lotto/RandomLottoGenerator.java
> +        final List<Integer> lottoNumbers = numbers.subList(0, LOTTO_NUMBER_COUNT);
`new ArrayList<>( numbers.subList(0, LOTTO_NUMBER_COUNT))` 가 어떨까요?
`subList()`에 사이드 이펙트가 많더라구요ㅜ

관령 링크를 공유합니다
[https://m.blog.naver.com/PostView.nhn?blogId=yjw2288&logNo=221072561904&proxyReferer=https%3A%2F%2Fwww.google.com%2F](https://m.blog.naver.com/PostView.nhn?blogId=yjw2288&logNo=221072561904&proxyReferer=https%3A%2F%2Fwww.google.com%2F)

2020-03-04 15:18 UTC, cglee079 commented on src/main/java/lotto/WinningNumbers.java
>          return number < LOTTO_MIN_NUMBER || number > LOTTO_MAX_NUMBER;
요 검증은 `bonusNumber`를 `LottoNo`로 파싱하면서 검증되지 않을까요?

2020-03-04 15:18 UTC, cglee079 commented on src/main/java/view/InputView.java
> +            return new ArrayList<>();
불변하는 `Collections.emptyList()`를 쓰는것도 좋을거같아요!

2020-03-04 15:18 UTC, cglee079 commented on src/main/java/lotto/LottoShop.java
> +        int lottoCount = inputMoney.availableLottoCount();
여기서 `Money`가 내부에  `LOTTO_PRICE` 상수 값을, 인자로 넘겨주는게 어떨까요 ?
그렇게 하면 메소드도 `divide()` 같은 좀더 일반화된 메소드를 사용할 수 있을것 같아요!

2020-03-05 07:49 UTC, junwoochoi commented on src/main/java/lotto/LottoShop.java
> +        assert inputMoney != null && manualLottoInputs != null;
앗...그러네요... 좋은 정보 공유 감사합니다!!!

2020-03-05 13:02 UTC, pasudo123 reviewed
코드 잘 보았습니다.
생각나는 부분들에 대해서 코멘트 남겨보았어요 :)

2020-03-05 13:02 UTC, pasudo123 commented on src/main/java/view/InputView.java
> +        }
수동 로또 번호 입력시, 지난주 당첨번호 입력처럼 `trim()` 메소드 처리를 해주는 게 어떨까요?
1, 2, 3, 4, 5, 6 과 같이 띄어쓰기 입력하면 에러가 발생할 수 있다고 생각해요.

2020-03-05 13:02 UTC, pasudo123 commented on src/main/java/lotto/LottoShop.java
> +        }
저도 동일하게 생각해보았어요.
sell() 메소드를 수동생성, 자동생성 메소드로 한번 더 잘게 나누어도 좋지 않을까요?

2020-03-05 13:02 UTC, pasudo123 commented on src/main/java/ConsoleMain.java
여기 부분은 아닌데 펼쳐서 보다보니, 여기에 코멘트 쓸 곳밖에 없더군요 ㅠ

__바로 아래줄__ 에 있는
`checkResults()` 메소드를 Main 함수가 해당 역할을 수행하기 보다,
ResultFactory 내부에서 Results 를 반환전에 수행하는 것에 대해서 어떻게 생각하세요?

2020-03-06 00:59 UTC, nokchax reviewed
수고하셨습니다, 래핑 클래스와 1급 컬렉션 적용을 한번 해보아요

2020-03-06 00:59 UTC, nokchax commented on src/main/java/lotto/Lottery.java
>      private Lottery(Set<Integer> lottoNumbers) {
이건 다른 분들의 생각이 궁금해서 논의해보고 싶은데,
생성자의 파라미터로 LottoNo을 넘겨주는 것과 Integer 컬렉션을 넘겨 주는 것 어떤게 더 좋을거 같나요?
저는 기왕 만들어둔 래핑 클래스를 인자로 넘겨주는 식으로 해뒀는데, 사실 테스트 시에는 오히려 더 불편한 점도 있었거든요.

2020-03-06 00:59 UTC, nokchax commented on src/main/java/lotto/Lottery.java
> +        return new TreeSet<>(numbers);
```suggestion
        return Collections.unmodifiableSet(numbers);
```
를 사용하면 어떨까... 라고 생각했는데 이러면 순서 보장이 안되려나..?

2020-03-06 00:59 UTC, nokchax commented on src/main/java/lotto/LottoShop.java
> +        assert inputMoney != null && manualLottoInputs != null;
공유 감사합니다

2020-03-06 00:59 UTC, nokchax commented on src/main/java/lotto/ManualLottoGenerator.java
> +        if (Objects.isNull(inputNumbers)) {
오 자바 유틸 클래스네요, 저도 써봐야겠어요 배워갑니다.

2020-03-06 00:59 UTC, nokchax commented on src/main/java/lotto/RandomLottoGenerator.java
> +        final List<Integer> lottoNumbers = numbers.subList(0, LOTTO_NUMBER_COUNT);
와 이런 이슈도 있네여, 배워갑니다.

2020-03-06 00:59 UTC, nokchax commented on src/main/java/lotto/WinningNumbers.java
>  public class WinningNumbers {
Lottery 클래스를 상속하면 어떨까요? 
WinningNumbers 클래스에서 getNumbers() 메소드나 validation()을 재사용하면 펀할거 같은데

2020-03-16 23:41 UTC, junwoochoi commented on src/main/java/ConsoleMain.java
그렇게 하는 게 더 깔끔하네요! 감사합니다 ㅎㅎ

2020-03-16 23:44 UTC, junwoochoi commented on src/main/java/lotto/Lottery.java
>      private Lottery(Set<Integer> lottoNumbers) {
음... 저 같은 경우 LottoNo 객체는 Lottery 클래스 내부에서 의미를 가진다고 생각해서 Lottery 클래스가 Integer를 이용해서 LottoNo 를 생성하도록 하였습니다.
저도 다른분들 생각은 어땠는 지 궁금하네요 ㅎㅎ

2020-03-16 23:48 UTC, junwoochoi commented on src/main/java/lotto/Lottery.java
> +        return new TreeSet<>(numbers);
순서 보장이 안되는 것 같아서 
```java
        return Collections.unmodifiableNavigableSet(new TreeSet<>(numbers));
```
로 수정해봤습니다 !

2020-03-17 00:12 UTC, junwoochoi commented on src/main/java/lotto/LottoShop.java
> +        }
두분 의견 들어보니 함수가 너무 길어서 메소드로 잘게 나누어 봤습니다! 감사하빈다 👍

2020-03-18 23:52 UTC, merged